# Generated by Django 3.2.8 on 2021-10-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('link', models.URLField(blank=True, max_length=1024, null=True)),
                ('technologies', models.CharField(blank=True, max_length=254, null=True)),
                ('techstack', models.CharField(choices=[('1', 'HTML'), ('2', 'CSS'), ('3', 'JavaScript'), ('4', 'Python'), ('5', 'CSS'), ('6', 'JavaScript'), ('7', 'Python'), ('8', 'CSS'), ('9', 'JavaScript')], default='1', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
