# Generated by Django 3.2.8 on 2021-10-26 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='techstack',
        ),
    ]
