# Generated by Django 3.2.8 on 2021-10-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
