# Generated by Django 3.2.8 on 2021-10-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='images_path'),
        ),
    ]
