# Generated by Django 4.0.4 on 2022-08-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
