# Generated by Django 5.2.1 on 2025-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
