# Generated by Django 5.2.4 on 2025-11-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
