# Generated by Django 5.2.4 on 2025-11-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_badge_project_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='badge_label',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
