# Generated by Django 5.2.4 on 2025-11-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_badge_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='badge_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
