# Generated by Django 5.2.4 on 2025-11-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_badge_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='badge_link_text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cert_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cert_link_text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
