# Generated by Django 5.2.4 on 2025-11-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal Project'), ('client', 'Client Work'), ('freelance', 'Freelance'), ('hackathon', 'Hackathon'), ('school', 'School Project'), ('open_source', 'Open Source')], max_length=50, null=True),
        ),
    ]
